### ISSUE TITLE
Translations not applied in the latest Obsidian version

### ISSUE THREAD

**Issue by y1ndan** [obsidianmd/obsidian-translations#1007]
Hi,

I noticed that some of the translated texts are not being applied in the Obsidian app, even though they have been translated in the JSON files. I am currently using version 1.6.5, which was released yesterday.

Here are some examples:
- Current in 1.6.5:
  ![image](https://github.com/obsidianmd/obsidian-translations/assets/53508617/6c2f9c35-34db-4276-bbb6-b61596d6ac6c)

- Download `zh.json` from this repo and use it in the developer console:
  ![image](https://github.com/obsidianmd/obsidian-translations/assets/53508617/609aafa4-192f-4b68-9af6-447a422ab06a)

Could you please clarify when the translation files will be integrated each time a new version is released?

Thanks.

**Comment by joethei** [comment]
Then translation changes have been integrated in the latest release.
