### ISSUE TITLE
Add a Danish .json template. 

### ISSUE THREAD

**Issue by AlbertosaurusrexDK** [obsidianmd/obsidian-translations#129]
As the title says, I'd like a Danish template for translating into Danish.

Thanks a lot!

**Comment by ericaxu** [comment]
I think we already have a Danish template: https://github.com/obsidianmd/obsidian-translations/blob/master/nl.json

**Comment by AlbertosaurusrexDK** [comment]
> I think we already have a Danish template: https://github.com/obsidianmd/obsidian-translations/blob/master/nl.json

No, that would be the Dutch template - I assume that this is named after the ISO 639-2, where Danish is `da` and Dutch is `nl`

**Comment by ericaxu** [comment]
Sorry about that! That's really silly of me.

Added Danish in afe665b.
