### ISSUE TITLE
Czech language

### ISSUE THREAD

**Issue by Inirdin** [obsidianmd/obsidian-translations#179]
Hello, I would like to help with translation into Czech.

**Comment by mafsi** [comment]
Read this: https://github.com/obsidianmd/obsidian-translations#readme

**Comment by Inirdin** [comment]
@mafsi I have read that, what did I do wrong?

**Comment by mafsi** [comment]
You don't have any obsidian project in your github.
[Read this section](https://github.com/obsidianmd/obsidian-translations#submit-changes)! 
You have to Fork the Obsidian Translation Repository. Then go to your language file. Click the pencil icon (top right). Then translate. After you finish scroll-down and press: Create pull request. Is all specify in Readme.

**Comment by Inirdin** [comment]
@mafsi There isn't .json file of my language. "If the language you want to translate doesn't exist as a JSON file yet, submit an issue so that we can create a template for you to get started."

**Comment by mafsi** [comment]
Do what i said. Then open en.json and rename it cz.json. Start working on that. After that submit a pull request and in Title & description tell them: New language added: Czech. Please add this to the language repository

**Comment by Inirdin** [comment]
@mafsi Alright, thanks. I though it could be done this way, but I wasn't sure if different languages don't have different templates than english.

**Comment by mafsi** [comment]
> but I wasn't sure if different languages don't have different templates than english.
No. There is the default template. The english one. Everyone is translating that into their language
