### ISSUE TITLE
No Translation for Tamil

### ISSUE THREAD

**Issue by AadharshAadhithya** [obsidianmd/obsidian-translations#199]
Tamil language is one of the six classical languages in India, An we'd like to see a Tamil translation for obsidian.md.  please create the corresponding template... :)

**Comment by mafsi** [comment]
Fork this repository and open `en.json`. Rename it `tam.json` or `ta.json` and start translate. I'm assuming that `tam` is modern language of Tamil [as it is showing here](https://en.wikipedia.org/wiki/Tamil_language).

**Comment by AadharshAadhithya** [comment]
Yea.. Sure.. Thanks ... 👍

**Comment by ericaxu** [comment]
Closed by #207 .
