### ISSUE TITLE
Translating the term 'Vault'

### ISSUE THREAD

**Issue by starise** [obsidianmd/obsidian-translations#224]
I thought a lot around the term "Vault" used by Obsidian and its current italian translation that, right now, is: "Cassaforte".

Before making changes i wanna share my opinion on this matter with authors/translators.

My concerns are due to the fact that "cassaforte" in italian is *specifically* referenced at what in english is more like a "strongbox": a box with a secure lock. Cassa-forte is, infact, a compound word (cassa=box, forte=strong, literally: a strong box).

In Italy to indicate a larger safe, for example a big safe room inside a bank, the french word "[caveau](https://it.wikipedia.org/wiki/Caveau)" is often used [instead of "cassaforte"](https://translate.google.it/#view=home&op=translate&sl=en&tl=it&text=safety+vault).

In conclusion, anything that's not a "box", small or relatively big, with a lock or a combination, like a "safe place" to store something, doesn't fit well the italian word "cassaforte". I also feel that the meaning of the term "vault" intended by Obsidian is more like: a place to store documents, notes and stuff. Not specifically inherent to its safeness but more to a "private, personal space". 

My doubts has been strengthened when I found that french translators use the word [projet](https://github.com/obsidianmd/obsidian-translations/blob/3d724181831fec9df6081a7fc1a7a2073656b67f/fr.json#L53) to translate "vault", even if a more literal translation is ["caveau" and not "projet"](https://translate.google.it/#view=home&op=translate&sl=fr&tl=en&text=caveau) (project).

I also took a look at other translators choices. For example the [german translator has left the english "Vault"](https://github.com/starise/obsidian-translations/blob/83f51cd97b5e13f2050e9bab8fb0e674a278a6bf/de.json#L53).

IMO the word projet/project (in italian: "Progetto") is less "faithful" to the original. Also because, I can't help but notice, the icon used to open Vaults in Obsidian is, of course, a vault/strongbox. 😄 This is why I suppose that using the english "Vault" is a better choice overall also in italian.

**Comment by cristianvasquez** [comment]
If you look at the icon of 'vault' it shouws a 'bank vault'

**Comment by starise** [comment]
Yes, I said it above. 😉 It's my strongest doubt on this matter! Anyway if you look the [thesaurus](https://www.thesaurus.com/browse/vault) for the word, "hot" synonyms are: basement, cellar, mausoleum, pit, tomb... I mean, in english this word has a wide meaning.

About "vault", [Merriam-Webster](https://www.merriam-webster.com/dictionary/vault) says:

> 1a: an arched  **structure** of masonry usually forming a ceiling or roof.
> 1b: something (**such as the sky**) resembling a vault.
> 1c: an arched or dome-shaped anatomical structure the  **cranial vault**
> 
> 2a :  a space covered by an arched structure especially : an underground passage or  **room**
> 2b : an **underground** storage compartment
> 2c : a **room** or compartment for the safekeeping of **valuables**

Only the last definition is "bank vault", as you said. Bold highlights above made by me, because I'd like to point out a couple of things (back to my translation problem): none of the definitions above is remotely close to the meaning of "cassaforte" in italian. The closest one is the last one (2c), but only if you want to indicate a "small compartment", not a room, because for wider spaces we use the french "caveau".

I **must** also notice that this word might suggest to english people, even if not in a direct manner, other words as: **structure**, **cranial vault**, **rooms** or even large spaces **such as the sky**. In Obsidian a vault is a collection of folder, sub-folders and files, a place that can be infinitely deep. Obsidian itself is a software that aspires to be a **second brain**, for making and following connections fostering a knowledge network. A tool for discovering connections **buried underground** in our minds. And these connections are shown as a graph of connected points that resembles a **vast starry sky**.

Honestly, I can't ignore these connections of meanings for a software like Obsidian. Maybe I'm overthinking it, but I feel the translation of this term in the context of Obsidian is very interesting. And, as for my native language, i feel that "cassaforte" is not a good match. I know that leaving Vault untranslated is a non-translation, but at least is neutral and maybe can encourage italian people to look deeper into the meaning of the original word.
