### ISSUE TITLE
Missing strings for titlebar and more

### ISSUE THREAD

**Issue by starise** [obsidianmd/obsidian-translations#242]
I've found some strings that appear to be missing on the original translation.

1. `Minimize`, `Maximize`/`Restore down`, `Close window`, and `Go back`, `Go forward` → Tooltips on top titlebar
2. `Cut`, `Copy`, `Paste` → Right click menu voices clicking on editor space.
3. `Enter or F3` and `Enter` Tooltips on Prev/Next buttons in editor search.
4. ~~`Obsidian plugins` → under `Settings > Options`~~

OS: Windows 10 Pro 20H2
App version: Obsidian v0.9.11

**Comment by ericaxu** [comment]
We can fix 1 and 3. 2 is on the native level, so unfortunately I don't think we're in a good position to fix that right now.

As of 4, where is that? Could you take a screenshot? Did you mean "Core plugins"?

![image](https://user-images.githubusercontent.com/1171143/100198507-efb73e80-2ec9-11eb-851d-6b99a98156ae.png)

**Comment by starise** [comment]
> We can fix 1 and 3.

👍 

> 2 is on the native level, so unfortunately I don't think we're in a good position to fix that right now.

I see. Hope you'll able to fix it later.

> As of 4, where is that? Could you take a screenshot? Did you mean "Core plugins"?

Oh sorry, it's gone, the latest version is ok!

**Comment by ericaxu** [comment]
Added, will be available soon. Sorry for the late reply!

**Comment by ericaxu** [comment]
Added in c8f993ef81444169576e02a86718cf40912b68b0.
