### ISSUE TITLE
Please add Urdu (ur.json) template.

### ISSUE THREAD

**Issue by viaahmed** [obsidianmd/obsidian-translations#327]
@ericaxu is it possible that we have two json files for same language?
I want to make two versions of the Urdu language. 
One in Roman script (urd.json) and other in Arabic/Persian script (ur.json).

**Comment by ericaxu** [comment]
Added in: https://github.com/obsidianmd/obsidian-translations/commit/ecaabc1d889e31ac6c95d318bc9aea8560c76343

Thanks for the proposal!
