### ISSUE TITLE
Two language strings in da.json are not updated in app

### ISSUE THREAD

**Issue by henrikfalk** [obsidianmd/obsidian-translations#350]
Two strings are not shown in Danish in Setting->Files & Links.

The strings are translated in the da.json file but as you can see on the image it is not in the app:

![Screenshot_20210201_173023](https://user-images.githubusercontent.com/30142914/106490652-518db900-64b6-11eb-8c55-e6a08382b22f.png)

Obsidian v0.10.12

da. json:
“option-new-attachment-location”: “Standard placering for nye vedhæftede filer”,
“option-new-attachment-location-description”: “Hvor nye vedhæftede filer er placeret.”,

I have not tested if any other languages have the same problem with these strings.

/Henrik :slight_smile:

**Comment by ericaxu** [comment]
Are those strings newly translated? It could lag behind 1-2 versions but not much more than that.

Thanks for understanding! We'll try to merge in the new translations as often as we can.

**Comment by henrikfalk** [comment]
No, they are not newly translated. As I remember they were in one of the first batches of translations I made.

The latest translations I made for v0.10.10 are working fine in v0.10.12.

I am just wondering why those two are not updated.

**Comment by ericaxu** [comment]
Sorry it's our mistake. It should get translated soon, there's nothing you need to do on your side.

Thanks for catching this!

**Comment by henrikfalk** [comment]
Fixed in v0.11.0
