### ISSUE TITLE
"Search options" is not in the language files

### ISSUE THREAD

**Issue by henrikfalk** [obsidianmd/obsidian-translations#351]
An user on Discord mentioned that all the strings in the "Seach options" is not translated.

Obsidian v0.10.12:
![Screen_Shot_2021-02-01_at_23 41 05](https://user-images.githubusercontent.com/30142914/106518550-55cbcd80-64da-11eb-8657-e73c3d62887b.png)

**Comment by ericaxu** [comment]
Thanks, will be fixed in the next update. I'll close the issue by then.

Good catch!

**Comment by henrikfalk** [comment]
I found some other issues related to this issue.
When I translated the "Plugin->Search" file in the Obsidian documentation I noticed that "SEARCH OPTIONS" in the app is not in sync with the documentation in section: "### Search operators".
"content:", "match-case:", "ignore-case:" and "block:" is not part of the operators you can choose in the dialog:

![Screenshot_20210212_152418](https://user-images.githubusercontent.com/30142914/107781028-b44d4300-6d47-11eb-8530-a781f3e42650.png)

And what about the search operators?
I think they should be translatable as well. 

/Henrik :)

**Comment by ericaxu** [comment]
Should be translatable by `label-path-option-description` etc now. Let me know if you still have issues.
