### ISSUE TITLE
Can hotkey labels be translatable?

### ISSUE THREAD

**Issue by henrikfalk** [obsidianmd/obsidian-translations#352]
Obsidian v0.10.12

Settings->Hotkeys

The labels "Blank", "Ctrl", "Enter", "Shift", "Alt" and properly a few other labels are not translatable in the languagefiles

![Screenshot_20210204_110137](https://user-images.githubusercontent.com/30142914/106878978-e07b1b00-66da-11eb-855d-e256756210a2.png)

**Comment by ericaxu** [comment]
We can add translation for "blank", but I'm not sure if it's necessary for the other keys. Keyboards made around the world have those keys labeled as Enter, Ctrl, Alt, if I understand correctly? (Although some layouts have additional modifier keys like AltGr.)

Are you aware of any other software that translates those modifier keys and Enter when set to your language? If it's not a convention, I'm afraid it would be counterproductive. We can definitely fix "Blank" though.

**Comment by starise** [comment]
In Italy some of these keys are usually labeled in italian:
- `Enter` => `Invio`
- `Shift` => `Maiusc`

But I suppose 99% of users are able to recognize them in english.

> Are you aware of any other software that translates those modifier keys and Enter when set to your language?

VS code definitely translate them:

https://github.com/microsoft/vscode-loc/blob/bb0e842697fa18e907cf0b0f10840296111ffad9/i18n/vscode-language-pack-it/translations/main.i18n.json#L60

Tbh I don't know why Ctrl, Alt and similar have translation strings, as you pointed out they're kind of standard worldwide, but maybe in some other languages this is not true.

**Comment by ericaxu** [comment]
Interesting!

Now "blank" is translatable -- should we close the issue now? @henrikfalk

**Comment by henrikfalk** [comment]
"blank" is working in v0.11.5.
