### ISSUE TITLE
Change "dansk" to "Dansk" in dropdownlist in language selection in app settings

### ISSUE THREAD

**Issue by henrikfalk** [obsidianmd/obsidian-translations#358]
Just a reminder that the first letter of "dansk" have to be capitalized and it is coded in the app.

The correct is: "Dansk".

![Screenshot_20210210_233711](https://user-images.githubusercontent.com/30142914/107617294-eaa79700-6c4f-11eb-9ac2-f1d0bb76bf50.png)

/Henrik :)

**Comment by ericaxu** [comment]
Done, will be released in 0.11.1.

**Comment by henrikfalk** [comment]
Verified that it is fixed in 1.11.1 :)
