### ISSUE TITLE
Greek support

### ISSUE THREAD

**Issue by eric-hansen** [obsidianmd/obsidian-translations#36]
ISO code is GR for it.

**Comment by ericaxu** [comment]
Wikipedia tells me the ISO code is `el`: https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=el

We're talking about modern Greek right?

**Comment by eric-hansen** [comment]
Dunno, I just Googled "ISO code for Greek" and it said it was GR heh.  If it's "EL" instead then we can roll with that.

**Comment by ericaxu** [comment]
Got it! Just making sure I'm not making a stupid mistake :)

**Comment by ericaxu** [comment]
Added in de58911. Thank you for the suggestion!
