### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by emilerl** [obsidianmd/obsidian-translations#368]
I can provide a Swedish translation if you create the template.

**Comment by henrikfalk** [comment]
I believe filename should be: "se,json" and native name: "Svenska" in the README.md if I am correct @emilerl ?

**Comment by emilerl** [comment]
@henrikfalk, yes, that's correct.

**Comment by ericaxu** [comment]
Should be fixed in https://github.com/obsidianmd/obsidian-translations/commit/7309651dc93038e1a80d798168d7e381eb6b7a85.
