### ISSUE TITLE
"There's already a file with the same name" String is not translatable

### ISSUE THREAD

**Issue by Write** [obsidianmd/obsidian-translations#370]
Thanks to Olive#3715 for reporting it to me via email !

![image](https://user-images.githubusercontent.com/541722/109222397-ff406f00-77b9-11eb-853e-9f7657afca8c.png)

**Comment by Write** [comment]
Also this one : 

![image](https://user-images.githubusercontent.com/541722/109302192-3efa6b80-7839-11eb-9177-0b0311a78d9a.png)

**Comment by ericaxu** [comment]
Even after `msg-file-already-exists` and `button-new-group` have been translated? If so, you may just need to wait a version or two.

**Comment by henrikfalk** [comment]
Both are translated correct in v0.11.5.
@ericaxu I think you can close this issue.
