### ISSUE TITLE
A new note is by default named: "Untitled".

### ISSUE THREAD

**Issue by henrikfalk** [obsidianmd/obsidian-translations#399]
A new note is by default named: "Untitled" until you change the name.

The word: "Untitled" is not in the list of words that can be translated.

**Comment by ericaxu** [comment]
@lishid Do you think there might be an issues to translate this string?

**Comment by lishid** [comment]
Should be ok to translate. We just need to make sure it doesn't contain any special characters or spaces.

**Comment by henrikfalk** [comment]
@lishid Yes, about special characters or spaces.

But usually there is a standard word in most languages used by software for new files. In Danish it is: "Unavngivet" which loosely translates to  "not named yet".

**Comment by ericaxu** [comment]
> Should be ok to translate. We just need to make sure it doesn't contain any special characters or spaces.

No spaces or no special spaces?

**Comment by ericaxu** [comment]
These strings will be translatable soon. Thanks!

**Comment by henrikfalk** [comment]
Ok in v0.12.4
