### ISSUE TITLE
"Loading Workspaces" message

### ISSUE THREAD

**Issue by henrikfalk** [obsidianmd/obsidian-translations#408]
When you start Obsidian on desktop, at least on my Linux, there is at short message inside the application windows: "Loading Workspaces".

I think it must be the workspace plugin.

This should at some point be able to be translated. And other startup messages if any from core plugins etc. 
I know this is not a high priority issue but a part of polishing the application for the final version.

**Comment by ericaxu** [comment]
Hi, it's not from the workspaces, it's the app's status message saying that it's trying to restore the last layout from the `workspace.json` file.

I'll see if I can get this string to be translated, thanks!

**Comment by ericaxu** [comment]
Will be translatable soon!

**Comment by ericaxu** [comment]
Looks like I can close this now: https://github.com/obsidianmd/obsidian-translations/blob/master/da.json#L454

Let me know if we should re-open it.
