### ISSUE TITLE
Several strings are still English

### ISSUE THREAD

**Issue by yo-goto** [obsidianmd/obsidian-translations#413]
I found several strings which I've already translated are still English. Pleaser fix them.

![community plugin sort-min](https://user-images.githubusercontent.com/50942816/113647424-cacba700-96c5-11eb-95e2-6da06e0da05c.png)
![Emac-style-min](https://user-images.githubusercontent.com/50942816/113647429-cc956a80-96c5-11eb-8c27-a0bd80d93e66.png)
![file exproler sort-min](https://user-images.githubusercontent.com/50942816/113647433-cd2e0100-96c5-11eb-96f9-d00b6071a703.png)
![google analytics-min](https://user-images.githubusercontent.com/50942816/113647434-cdc69780-96c5-11eb-8c6b-3dc5bd4fa9e8.png)
![remoet vault-min](https://user-images.githubusercontent.com/50942816/113647436-ce5f2e00-96c5-11eb-938f-46580c231cde.png)
![serarch option-min](https://user-images.githubusercontent.com/50942816/113647438-ce5f2e00-96c5-11eb-89f4-320814b30c4b.png)
![sync-min](https://user-images.githubusercontent.com/50942816/113647439-cef7c480-96c5-11eb-9767-9dd19e1a7dde.png)
![tag pane sort-min](https://user-images.githubusercontent.com/50942816/113647443-cf905b00-96c5-11eb-98a0-7679c7f76d0c.png)

**Comment by ericaxu** [comment]
How long ago were they translated? It might lag a few versions. We'll update the translations -- please close the issue when you see it. Thanks!

**Comment by yo-goto** [comment]
Nope. I think this might be a bug. 
For example, first translation commit about sort order in File explorer was so long ago.(6 months ago)
![commit history](https://user-images.githubusercontent.com/50942816/113656034-f787ba80-96d5-11eb-9138-0d87bf17642b.png)
I checked these strings were translated in some old versions.

In other languages, these are still English. It's strange.
![italian](https://user-images.githubusercontent.com/50942816/113656202-52211680-96d6-11eb-9ea8-ebc626f61853.png)
![中文](https://user-images.githubusercontent.com/50942816/113656207-55b49d80-96d6-11eb-9b0a-f9b50d7bb21e.png)

**Comment by henrikfalk** [comment]
I can verify that most of @yo-goto findings are correct. They are still in English.
I cannot verify Sync or Publish as I do not have the services to test.

**Comment by henrikfalk** [comment]
The ones I can verify are fixed in v0.12.0 when using Danish language.

**Comment by yo-goto** [comment]
Me too. I checked.
