### ISSUE TITLE
missing description of file icon

### ISSUE THREAD

**Issue by ghost** [obsidianmd/obsidian-translations#451]
The description of the file icon (open additional notes in left and right sidebar) is missing in v0.11.13 (German). Maybe add placeholder like 'untitled' or 'new note' or just remove the empty text field?

**Comment by ericaxu** [comment]
Is it fixed in 0.12.1?

**Comment by 7aqdxe6f** [comment]
Not in v0.12.3, so probably neither in v0.12.1.
