### ISSUE TITLE
not all text under search field translatable

### ISSUE THREAD

**Issue by 7aqdxe6f** [obsidianmd/obsidian-translations#452]
Not all strings in the dropdown menu of the search field in the left pane seem to be translatable at the moment.

Edit: Version: v0.11.13, German.

**Comment by henrikfalk** [comment]
@7aqdxe6f  Which version? Which language?
No problems in v0.12.1 here in Danish. All descriptions are translated.
The search keys: "path, file, tag, line, section" are not translated though.

**Comment by 7aqdxe6f** [comment]
Sorry, forgot to add the version info.

Just switched to Danish and in v0.11.13 the description isn't translated yet. So v0.12.1 seems to add the translation for those.
