### ISSUE TITLE
Several commands are still English

### ISSUE THREAD

**Issue by yo-goto** [obsidianmd/obsidian-translations#466]
These commands are not translated.
- `Show tag pane`
- `Show outline pane`
- `Show starred pane`
- `Show file explorer`
- `Show outline pane`
- `Open outline of the current file`
- `Toggle backlinks in document`
- `Toggle comments for selection`
- `Toggle spellcheck`

![image](https://user-images.githubusercontent.com/50942816/118131809-f31f9180-b439-11eb-9b22-af421b865930.png)

**Comment by henrikfalk** [comment]
I can verify this.
Version 0.12.3 using "Danish" as language.
They are not in the translation file either.

**Comment by ericaxu** [comment]
Just pulled the new translations, should be fixed in 0.12.4

**Comment by yo-goto** [comment]
I confirmed this bug is fixed in v0.12.4
Thank you Silver.
