### ISSUE TITLE
Add new language - Malay (MY)

### ISSUE THREAD

**Issue by MagusWyvern** [obsidianmd/obsidian-translations#467]

**Comment by ericaxu** [comment]
Sure, we can add that!

From my research, the language code seems to be `ms`. Is that correct? And should the name of the language in its own language "Bahasa Melayu" or "بهاس ملايو"?

Source: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by MagusWyvern** [comment]
Yep! ```ms``` is correct. The name of the language in its own language is "Bahasa Melayu".

"بهاس ملايو" is just "Bahasa Melayu" written in another form of characters

**Comment by ericaxu** [comment]
Added in https://github.com/obsidianmd/obsidian-translations/commit/89c6db79c82a6e0f8d7e8aa9c80cddff8517f1da

Thanks!
