### ISSUE TITLE
Add new language - Serbian - RS

### ISSUE THREAD

**Issue by vuskovic09** [obsidianmd/obsidian-translations#468]

**Comment by ericaxu** [comment]
Hi there, thanks for the request!

Is Serbian's code `rs` or `sr`? I'm a little confused and would appreciate some help: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by ericaxu** [comment]
@vuskovic09 Hi! Did you get a chance to see my comment above?

**Comment by vuskovic09** [comment]
Apologies, I wasn't able to check this until today. I apparently made a typo without noticing, it is, indeed SR

**Comment by ericaxu** [comment]
Added, thanks for the suggestion!
