### ISSUE TITLE
Use Weblate

### ISSUE THREAD

**Issue by Porrumentzio** [obsidianmd/obsidian-translations#483]
I think that such a project as Obsidian would benefit a lot of using some online translation platform as Weblate, which can be [selfhosted](https://docs.weblate.org/en/latest/admin/install.html) or use other instances (https://hosted.weblate.org is the official one).

There glossaries can be used by default, so no need to create `xx.termbase.md` files. Also Weblate helps to keep consistence into translations by proposing similar strings already translated.

**Comment by ericaxu** [comment]
Thanks for the suggestion! Really appreciate it.

Took a brief look and didn't find features that we're lacking. I think the biggest con of GitHub is that not many people are technical enough to contribute, but we don't need that many translators for each language. There's also the issue of integrating the translation into the app, and it seems much more troublesome with a third-party solution. We'll carry over our plain text ethos to the translation realm 😄 just edit the text files!
