### ISSUE TITLE
Add Belarusian please

### ISSUE THREAD

**Issue by SpadarShut** [obsidianmd/obsidian-translations#486]
Please add a file for Belarusian language (BE).

And I have a question, how can I test my translation locally?

**Comment by ericaxu** [comment]
Added in 99c2f80.

> And I have a question, how can I test my translation locally?

Sorry there's no way to translate it locally yet. When it gets added you can see it in the next release. In general we try to group the text by group so it shouldn't be too hard to find. Some may request Sync or Publish subscription to see the UI.

In general we encourage you to translate as how you understand it and post an issue here if you encounter any issues. I hope that helps!
