### ISSUE TITLE
Adding json file for Albanian (AL)

### ISSUE THREAD

**Issue by gerd-alliu** [obsidianmd/obsidian-translations#494]
Hello everyone, 

I would like to help with the translation to Albanian, which is my native language. 

Cheers!

**Comment by ericaxu** [comment]
Is the language Albanian (Shqip)? The ISO code seems to be `sq` from my research.

Could you confirm that we can use `sq.json` for Albanian? Thanks.

https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by gerd-alliu** [comment]
Yes, `sq.json` would be great. 

Thank you!

**Comment by ericaxu** [comment]
Added in https://github.com/obsidianmd/obsidian-translations/commit/e26d9bd6e19e6f4962251d1e68149fa6d53ce593, thanks!
