### ISSUE TITLE
English translation wrong textblocks for split horizontally and vertically

### ISSUE THREAD

**Issue by amalic** [obsidianmd/obsidian-translations#508]
Should be the other way around
![image](https://user-images.githubusercontent.com/3675484/124350513-67ceab00-dbf5-11eb-80b5-df207470f0b9.png)

**Comment by tyindeepit** [comment]
As I understand, splitting horizontally is to cut something in left-right direction, leaving 2 things on top of each other. In the same way splitting vertically is in up-down direction, leaving 2 things next to each other. So I think the current usage here is not wrong.

With that said, Emacs and Vim use different terms for the same result. So to avoid more confusion, I suggest we change the terms to `Split left/right` and `Split top/bottom` instead?

**Comment by ericaxu** [comment]
Will be adjusted in 0.16. Thanks for the suggestion!
