### ISSUE TITLE
Obsidan Sync messages not translated in desktop app

### ISSUE THREAD

**Issue by henrikfalk** [obsidianmd/obsidian-translations#520]
After purchasing Sync I found that the sync status in the desktop app is not translated.
They seems not to be in the translation file.

![Screenshot_20210714_155232](https://user-images.githubusercontent.com/30142914/125640134-b2f430ef-bd83-456c-8a86-9f027caf8891.png)
![Screenshot_20210714_155252](https://user-images.githubusercontent.com/30142914/125640136-d418fe90-4ab6-4732-8473-99bc6b30a858.png)

I have not seen any other status messages but please check.

**Comment by ericaxu** [comment]
Should be updated now... probably just a lag on updates on our part.
