### ISSUE TITLE
Obsidian Sync - "Create" button in create external box dialog is not translated

### ISSUE THREAD

**Issue by henrikfalk** [obsidianmd/obsidian-translations#521]
Seems not to be in the translation file:

This is the dialog:
![Screenshot_20210714_153749](https://user-images.githubusercontent.com/30142914/125640898-fd0602b4-8e6d-41b1-88c3-b4916350a7b3.png)

**Comment by yo-goto** [comment]
I confirmed this. It's note translated.
![img_remoteVaultCreate](https://user-images.githubusercontent.com/50942816/126058778-6204a0cf-9910-4442-9906-b301fe6413f0.png)

**Comment by ericaxu** [comment]
Is this still an issue? If not I'll close this @henrikfalk @yo-goto

**Comment by yo-goto** [comment]
yep. still the issue.

<img width="628" alt="image" src="https://user-images.githubusercontent.com/50942816/164226775-8ebca4ef-f258-448e-a508-9d08e0e3f946.png">

**Comment by henrikfalk** [comment]
Tried to verify in v0.15.1 but I have used my 5 slots so I cannot really verify if the problem still exists.

**Comment by ericaxu** [comment]
Should be fixed in 0.15.3, sorry about that!
