### ISSUE TITLE
Right click options not translated in desktop app

### ISSUE THREAD

**Issue by yo-goto** [obsidianmd/obsidian-translations#522]
Right click options such as Cut/Copy/Paste are not translated.
![img_rightclickoptions](https://user-images.githubusercontent.com/50942816/126058606-f0c4e5c1-47fe-49cb-82be-60f52d27782a.png)

**Comment by henrikfalk** [comment]
Obsidian desktop v0.12.10 Danish translation works:
![Screenshot_20210718_140627](https://user-images.githubusercontent.com/30142914/126066408-92e83f04-3929-455e-8b23-5c1eb425e8de.png)
 I committed a few days before your Japanese version. Maybe I just got lucky to be included in the v0.12.10 version?
I can see your strings in ja.json are translated so maybe they are included in next build.

**Comment by yo-goto** [comment]
Oh, you seem right. The latest release doesn't include 2 weeks ago PR.

**Comment by ericaxu** [comment]
@yo-goto Sorry about that, will bundle it for the next insider release!
