### ISSUE TITLE
German word for color is written wrong ("Fareb -> Farbe")

### ISSUE THREAD

**Issue by wechlertj** [obsidianmd/obsidian-translations#525]
Hey in this line is the word Farbe written wrong. The word should be written "Farbe".

https://github.com/obsidianmd/obsidian-translations/blob/560e06fd6f766c9530b8bcd5412d5ad5aed02800/de.json#L709

**Comment by ericaxu** [comment]
Do you want to fix it yourself? You can use the GitHub UI to edit the file and submit a pull request.

**Comment by wechlertj** [comment]
I done a pull request. hope I did it the right way.
