### ISSUE TITLE
Meaning of Vault

### ISSUE THREAD

**Issue by konhi** [obsidianmd/obsidian-translations#535]
While working on [polish](https://github.com/obsidianmd/obsidian-translations/blob/master/pl.json) translation, I've stumbled upon a problem with semantic meaning of **Vault**. I asked on these Discord channels:
1. [#polish](https://discord.com/channels/686053708261228577/834513994735288380/870339752283496509)
2. [#translations](https://discord.com/channels/686053708261228577/741594204769222719/871707838865637416)

Unfortunately, there was no consensus. Here are few variations that were suggested by users.

1. sejf (it seems it's an icon in Obsidian)
![image](https://user-images.githubusercontent.com/61631665/128749750-5616fbd8-6c86-4d3f-9815-d0993427abb1.png)

2. skarbiec (used in Spanish, according to argentum#3920)
![image](https://user-images.githubusercontent.com/61631665/128749940-c6021d37-5ac6-4424-970f-b60f167392c9.png)

3. skrytka
![image](https://user-images.githubusercontent.com/61631665/128749990-bc35dde3-c453-4621-9926-9b471be53a0e.png)

4. Vault (no translation, used in German, according to FloriF#1816)

My questions are:
1. what is a correct representation suggested by Obsidian developers?
2. if translation is different than suggested in above, should this be changed?
3. should this suggestion be present in [README](https://github.com/obsidianmd/obsidian-translations/blob/master/README.md)?

This was discussed in #224, but I believe the answer is still not fully clear, common nor official.

**Comment by ericaxu** [comment]
From our perspective, it's closest to 1.

Although the word "vault" has many more meanings in English, so that might have contributed to the word choice. Can't say the same for the other languages, so please use your judgement. Thanks for asking!

**Comment by konhi** [comment]
Thanks!
