### ISSUE TITLE
Wrong spelling of title for new notes

### ISSUE THREAD

**Issue by SamAdams51** [obsidianmd/obsidian-translations#584]
Currently new notes get the default name „ Unbennant“. The spelling is wrong it has to be „Unbenannt“.

Thanks for a very good translation of the Obsidian GUI.
Helmut

**Comment by johannesdewit** [comment]
I think this is correct in the [the most recent German file, line 650 and 651](https://github.com/obsidianmd/obsidian-translations/blob/eee8fdfc39c89bddc247e2c0c0e2f4f73d6ffb1a/de.json#L650). This might still need to be update in the software, but I do not know more about that.

**Comment by ericaxu** [comment]
Will be updated in the next version.
