### ISSUE TITLE
Where should I put the translated .json file to test the translation?

### ISSUE THREAD

**Issue by VKondakoff** [obsidianmd/obsidian-translations#6]
Where should I put the translated .json file to test the translation?
Thanks!
(macOS)

**Comment by ericaxu** [comment]
The translations are dynamically loaded, so unfortunately there's no good way to test. (Also the translation system will be released in 0.8.3 so it's not available now.)

If you have trouble finding where a piece of text is, let us know. Most should be self-explanatory though.
