### ISSUE TITLE
Brazilian Portuguese ( pt-br)

### ISSUE THREAD

**Issue by GiancarloJSantos** [obsidianmd/obsidian-translations#60]
Hi there!

Can you guys create a Brazilian Portuguese template?

I´m very glad to help.

TIA.

**Comment by ericaxu** [comment]
Sure. Do you want to have the current Portuguese translation as a starting point, or would you like to translate fresh from the English template?

I guess by that I'm asking how different the two language variations are. If they are very different, maybe translating directly from English might be better.

Let me know! Thanks again.

**Comment by DavidsonTwo** [comment]
IMO, it's better to translate it directly from English

**Comment by ericaxu** [comment]
Added in e55cb39aab0e0505bd810fc47c8723bd0c88220c.
