### ISSUE TITLE
Translation to Bengali

### ISSUE THREAD

**Issue by jabidishtiaque** [obsidianmd/obsidian-translations#600]
Hello guys,

I want to help translating Obsidian to Bengali, which is my native language.
Bengali is the [fifth most-spoken native language](https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers) and the [sixth most spoken language](https://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers) by total number of speakers in the world.

- Language code: bn
- Language name: Bengali 
- Native name: বাংলা

**Comment by ericaxu** [comment]
Added in https://github.com/obsidianmd/obsidian-translations/commit/50ad1690fdf2387e86eecb0f5a5cc75fa1ca9235. Sorry for the late reply!

**Comment by Srinjoy-Santra** [comment]
Hello folks.

Translation to Bengali has not been picked up for more than a year. 

If no one's working on it, can I pick it up?

**Comment by ericaxu** [comment]
> Hello folks.
> 
> Translation to Bengali has not been picked up for more than a year.
> 
> If no one's working on it, can I pick it up?

Sure, please go ahead and open a PR after you're done!
