### ISSUE TITLE
Translation to Occitan

### ISSUE THREAD

**Issue by LoSolelh** [obsidianmd/obsidian-translations#607]
Hello,

I'd be interested to translate the software to Occitan !
If you need any more information don't hesitate !

**Comment by ericaxu** [comment]
Added in https://github.com/obsidianmd/obsidian-translations/commit/37bf1202c781b89fdcc55d37fc737215c6018aac. Not too sure what's Occitan called in Occitan, feel free to correct the README file. Thanks!

Sorry about the delay.
