### ISSUE TITLE
Add new language - Hungarian - hu

### ISSUE THREAD

**Issue by sunarch** [obsidianmd/obsidian-translations#621]
Hi,

I would like to translate Obsidian to Hungarian, which is my native language.

ISO 639-1: `hu`
[Wikipedia (en): Hungarian language](https://en.wikipedia.org/wiki/Hungarian_language)

**Comment by ericaxu** [comment]
Added in https://github.com/obsidianmd/obsidian-translations/commit/b5a6285d4cb94ff945a996fb66ce5347166f3a51
