### ISSUE TITLE
Incorrect language codes for some languages

### ISSUE THREAD

**Issue by Fevol** [obsidianmd/obsidian-translations#623]
I'm currently developing a plugin that makes heavy use of localizations. While testing, I noticed that some language codes do not entirely match up with the 'correct' IETF BCP 47 language codes, which makes it harder to get the corresponding localization.

Following language codes are not (fully) compliant with the standard:
- `tam` should be `ta` (the rest of the language codes in this repo are using the 639-1 standard, so this should be the two letter code)
- `cz` should be `cs`, cz is not the correct language code for the Czech language

**Comment by ericaxu** [comment]
Should be fixed with https://github.com/obsidianmd/obsidian-translations/commit/3ac69e0068e0163e7449dde2bd9827047bd99ae7.
