### ISSUE TITLE
Farsi (Persian) translation is not updated to the latest version.

### ISSUE THREAD

**Issue by AliKhomami** [obsidianmd/obsidian-translations#627]
Hello, I noticed that the strings in the Farsi translation are not updated to the latest version, also Farsi is still not available as a display language on Obsidian.
I would really appreciate it if you could fix these issues.
Thanks in advance!

**Comment by ka1tzyu** [comment]
Obsidian translations are more "community driven" and main developers don't participate. So if you want to actualize this translation, you can do it by yourself. And when it completes, open issue corresponding to adding your updated translation to Obsidian
