### ISSUE TITLE
Request a translation template: Sinhala (සිංහල)

### ISSUE THREAD

**Issue by thanushkas** [obsidianmd/obsidian-translations#639]
Hi,
Could you please create a translation template for the Sinhala (සිංහල) language, a language uses by majority People of Sri Lanka?

Thank you.

**Comment by joethei** [comment]
Sorry for the very long wait.
Do you intend on working on the translation?

**Comment by thanushkas** [comment]
Hi Johannes,
Thanks for your reply.
Yes, I'm looking for on working on the translation - Sinhala.

Appreciate your help.

Best regards,
Thanushka

**Comment by joethei** [comment]
The template is now available, sorry for the long wait.
