### ISSUE TITLE
Untranslated string

### ISSUE THREAD

**Issue by yo-goto** [obsidianmd/obsidian-translations#642]
`en.json` file is missing this string.
![img_untranslated](https://user-images.githubusercontent.com/50942816/176888095-9c0e816d-e684-411f-9ee8-f0b048a4d2f1.jpg)

**Comment by henrikfalk** [comment]
Mine looks like this and everything is translated:
![Screenshot_20220720_110428](https://user-images.githubusercontent.com/30142914/179943270-f10586d2-0209-4a2b-b013-c55d0a463cc2.png)

**Comment by liamcain** [comment]
Thanks @yo-goto, I'll fix this for the next version.

**Comment by yo-goto** [comment]
Thank you!
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/50942816/180633680-61c4c139-c357-4375-bdb3-09d6fa8ba249.png">
