### ISSUE TITLE
Request a translation template: Galician

### ISSUE THREAD

**Issue by pepellou** [obsidianmd/obsidian-translations#646]
Hi,

Could you add a template for translations into Galician? (spoken by people in Galicia, Spain)
Language code `gl`, native language name `Galego`.

I'm native and would help writing the translations 🙂 

Thank you!

**Comment by albertoDOM** [comment]
Hello
Same request as @pepellou 

Thanks in advance

**Comment by ericaxu** [comment]
Added in https://github.com/obsidianmd/obsidian-translations/commit/4a77ea5791c8b9fd3d65dc8a967e7fd04bd1191b
