### ISSUE TITLE
German translation · Einheitliche Wortstellung

### ISSUE THREAD

**Issue by confluencepoint** [obsidianmd/obsidian-translations#66]
@Cherubeam: Bei der deutschen Übersetzung sollte auf eine **einheitliche** Wortstellung geachtet werden. Das Verb im ***Infinitiv*** sollte am Ende der Strings stehen. 

Auf Wörter wie _schalten_, _setzen_ sollte verzichtet werden. Das mag zwar umgangssprachlich richtig sein, für eine gute Übersetzung sind diese Verben aber ungeeignet.

*Beispiele:*
`"option-community-themes": "Öffne Community-Themes",`
"Öffne Community-Themes" ⇢ "Community-Themes öffnen"

`"option-spellcheck-description": "Schaltet die Rechtschreibprüfung ein. Funktioniert derzeit nur für Englisch (US).",`
"Schaltet die Rechtschreibprüfung ein. …" ⇢ "Rechtschreibprüfung aktivieren. Derzeit nur für Englisch (US) verfügbar."

Standardmodus sollten wir in *Erscheinungsbild* ändern. Das hätte den Vorteil, dass *Heller Modus* und *Dunkler Modus* in **Hell** und **Dunkel** geändert werden könnte. Zumal Erscheinungsbild mehr auf die _Darstellung_ abzielt.

**Comment by Cherubeam** [comment]
@confluencepoint: Ich stimme dir zu. Ich habe nicht auf die Wortstellung geachtet.

Bezüglich _schalten_, _setzen_ würde ich nicht generell zustimmen, aber ich habe selbstverständlich kein Problem damit, passendere Verben zu nutzen.

Bezüglich _Erscheinungsbild_ stimme ich dir ebenfalls zu. Mir ist ad hoc keine passendere Übersetzung für _Base mode_ eingefallen.

**Comment by ericaxu** [comment]
I really want to understand the conversation, but I'm afraid I don't... 😬 

Could someone give us a summary of what to do or whether the issue can be closed, if you need us to? Thanks in advance!

**Comment by Cherubeam** [comment]
@ericaxu sorry, I just got aware of that we were writing in German :D 
Basically the issue is actually more a discussion about the order of words in the sentences I translated.
I don't think that you can do much here and think this issue can be closed.
The solution will be by changing the word order incrementally by several contributors for this translation file.
I hope tha helps.

**Comment by ericaxu** [comment]
@Cherubeam Thanks, that helps a lot! I'll close this issue for now. 👍
