### ISSUE TITLE
Request a translation template: Nynorsk

### ISSUE THREAD

**Issue by hsherl** [obsidianmd/obsidian-translations#666]
Hei! 

Could you please add a template for translations into Nynorsk (nn)? 

It is the written language in Norway alongside Bokmåk (no), which already exists in the list here. Bokmål and Nynorsk are quite similar, but it is an important matter for some Norwegians to have their dialects better represented in written language, which is (roughly speaking) what Nynorsk does. 

I'm native and would help writing the translations! 

Thank you!

**Comment by joethei** [comment]
Added the template just now, sorry for the long wait.

Thank you for volunteering.
