### ISSUE TITLE
 Translation error (German)

### ISSUE THREAD

**Issue by mklengel** [obsidianmd/obsidian-translations#673]
Steps to reproduce
Hover over “Workspace-Layouts” Icon

Expected result
Workspace-Layouts verwalten

Actual result
Workspace-Layouts verewalten

Environment
Operating system: W11
Debug info:
SYSTEM INFO:
Obsidian version: v0.15.9
Installer version: v0.15.9
Operating system: Windows 10 Pro 10.0.22000
Login status: logged in
Catalyst license: none
Insider build toggle: off
Live preview: on
Legacy editor: off
Base theme: dark
Community theme: Cybertron
Snippets enabled: 0
Restricted mode: off
Plugins installed: 9
Plugins enabled: 9
1: Better Word Count v0.8.1
2: Hotkeys++ v0.2.7
3: Sliding Panes (Andy’s Mode) v3.3.0
4: Calendar v1.5.10
5: Note Refactor v1.7.1
6: Advanced Tables v0.17.3
7: Dataview v0.5.41
8: Templater v1.12.0
9: Excalidraw v1.7.12
![Screenshot 2022-08-12 164959](https://user-images.githubusercontent.com/2345934/184403121-bcdd42ce-1926-4855-9b0b-02272d304ffa.png)

**Comment by adueck11** [comment]
Corrected and opened a pull request #674
