### ISSUE TITLE
Some errors in french version

### ISSUE THREAD

**Issue by rereviewer** [obsidianmd/obsidian-translations#676]
Hi! As a french user, I noticed that when I click on Insert + Folding, there is an error, as you can see on the picture below and if you know french language. It is written: “tour déplier” instead of “Tout déplier”.

If I can add something: in french, “liste à numéro” must be written “liste à numéros” ou “liste numérotée”.

![e02b33b61fbbd8f26fd4ebf582ba853a1f064e8f_2_690x444](https://user-images.githubusercontent.com/112067980/186607568-83038f58-951d-425a-a1d1-641ed117a5eb.jpeg)

**Comment by johannesdewit** [comment]
I have fixed the mentioned issues. See https://github.com/obsidianmd/obsidian-translations/pull/677.

Now we wait until the pull request is approved!

**Comment by joethei** [comment]
The fix has been merged

**Comment by rereviewer** [comment]
Hi everyone! I did not find how to send a new translation. Therefore, I'm writing it here. On the screenshot below, you'll find some errrors: I understand the first red boxed text as follows: "Il n'est actuellment plus **mis à jour**". The second red boxed text must be fixed as follows, removing the last "s": "par conséquent".  
Thanks for your work.

 
![screenshot](https://user-images.githubusercontent.com/112067980/198599319-6f7cd216-f0dd-44a2-b40d-4c1cedaed1f1.jpg)
