### ISSUE TITLE
Request a translation template: Latvian

### ISSUE THREAD

**Issue by janovsk1s** [obsidianmd/obsidian-translations#678]
Hi!

Could you please add a translation template for Latvian?

the Language code would be **lv**, and the native language name would be **Latviešu valoda** 🇱🇻

Thank you!

**Comment by ericaxu** [comment]
Added in [3411714](https://github.com/obsidianmd/obsidian-translations/commit/34117147dec7ed328d8b6bc616a7e40b57d2ea5e)

Thanks in advance!
