### ISSUE TITLE
Request a translation template: Esperanto

### ISSUE THREAD

**Issue by bellakine** [obsidianmd/obsidian-translations#679]
Bona tago!

I was wondering if a template for Esperanto could be added? I conduct the majority of my vault in Esperanto and I would like to help add it as a language! The language code would be `eo`.

Thank you!

**Comment by ericaxu** [comment]
> Bona tago!
> 
> I was wondering if a template for Esperanto could be added? I conduct the majority of my vault in Esperanto and I would like to help add it as a language! The language code would be `eo`.
> 
> Thank you!

What's Esperanto in Esperanto btw? Is it "Esperanto"?
