### ISSUE TITLE
"Zoom level" and its description in settings is not in "en.json"

### ISSUE THREAD

**Issue by henrikfalk** [obsidianmd/obsidian-translations#688]
The string "Zoom level" and its description is missing in en.json.

Here is a screenshot from the Danish translation:
![Screenshot_20221014_061356](https://user-images.githubusercontent.com/30142914/195762391-7028b658-d13f-4121-a755-1ac0255a9b1e.png)

**Comment by liamcain** [comment]
Oops, good catch! I'll fix this soon.

**Comment by ericaxu** [comment]
> Oops, good catch! I'll fix this soon.

Can we close this yet?

**Comment by liamcain** [comment]
This will get fixed in the next release.
