### ISSUE TITLE
Request a translation template: Finnish

### ISSUE THREAD

**Issue by Pasark** [obsidianmd/obsidian-translations#697]
Hi,

Could you provide us with a template for Finnish to work on? The language code is fi-fi and the native name is 'suomi'

I also would want to participate in the effort as a native speaker.

Have a good one!

**Comment by tatupesonen** [comment]
I'm also available to help.

**Comment by ericaxu** [comment]
> Hi,
> 
> Could you provide us with a template for Finnish to work on? The language code is fi-fi and the native name is 'suomi'
> 
> I also would want to participate in the effort as a native speaker.
> 
> Have a good one!

Can I ask why not just `fi.json`? Which language code are you referencing? We usually use the 2-letter language code unless there's a collison.

**Comment by liamcain** [comment]
Added a Finnish template here: <https://github.com/obsidianmd/obsidian-translations/blob/master/fi.json>

**Comment by Pasark** [comment]
Thank you! fi is fine. Finland has two official languages, Swedish and Finnish. fi-fi is used for Finnish finnish and fi-sv is Finnish swedish. fi and sv works fine since there are only minor differences in swedish in Finland and Sweden. No collision.

**Comment by tatupesonen** [comment]
@Pasark If you're interested, I've started a small repo which could have the combined effort of the Finnish translations. It would be great to work on this with other Finnish translators :) Here's the link to the repository:
https://github.com/tatupesonen/obsidian-translations/tree/translation-languages/finnish

**Comment by ericaxu** [comment]
> @Pasark If you're interested, I've started a small repo which could have the combined effort of the Finnish translations. It would be great to work on this with other Finnish translators :) Here's the link to the repository: https://github.com/tatupesonen/obsidian-translations/tree/translation-languages/finnish

Great effort! Please make sure you still PR to this repo to make your translation visible in the app, thank you!

**Comment by tatupesonen** [comment]
@ericaxu Yup! We have a draft PR open and I'll mark it as mergeable once we have some work done on the translations.

**Comment by Pasark** [comment]
@tatupesonen Mukana ollaan 👍
