### ISSUE TITLE
Core Plugin

### ISSUE THREAD

**Issue by Gr-Nobel** [obsidianmd/obsidian-translations#716]
One problem with the daily note core plugin .
I can easily jump to today's daily note from anywhere of obsidian. But  to go one day backward in my calendar from where I'm right now is a really needed feature . 

### **Example:** I'm on the august 29 .I press a hotkey i go back in my daily note to august 28 .Press the hotkey again jumps to august 27. I press another hotkey to go to august 28 then to august 29.

_Some people use templater to paste the previous day and next day as a link. But it creates a lot of unnecessary links. That doesn't suit Obsidian._

**Comment by joethei** [comment]
Please submit bug reports/feature request on our forum: <https://forum.obsidian.md>
