### ISSUE TITLE
Requesting Translation Template: Telugu

### ISSUE THREAD

**Issue by chinnidiwakar** [obsidianmd/obsidian-translations#726]
Hi, i would like to request to provide translation template for Telugu Language. i have previously worked on Niagara Launcher Translations for the same language too.

the language code can be te-in, and the native name is తెలుగు

**Comment by ericaxu** [comment]
> Hi, i would like to request to provide translation template for Telugu Language. i have previously worked on Niagara Launcher Translations for the same language too.
> 
> the language code can be te-in, and the native name is తెలుగు

The two letter language code is `te` from my research, is `te-in` a more specific code?

I added it in https://github.com/obsidianmd/obsidian-translations/commit/98822786a3ed88965612af358a7916427515b8a2 btw. Thanks in advance for your translations!

**Comment by chinnidiwakar** [comment]
Hi te is telugu

te-in

Is like

en-us

or en-uk

Like that

Telugu-India= te-in

4 జన, 2023, బుధ 12:12 AMకి, Erica Xu ***@***.***> ఇలా రాశారు:

**Comment by chinnidiwakar** [comment]
Thanks for the support. I will start rightaway

4 జన, 2023, బుధ 1:48 AMకి, Chinni Diwakar ***@***.***> ఇలా
రాశారు:
