### ISSUE TITLE
"label-do-not-ask-again": seems not implemented in gui

### ISSUE THREAD

**Issue by henrikfalk** [obsidianmd/obsidian-translations#736]
In the dialogue delete file or folder the "label-do-not-ask-again" aka "Don't ask again" is not translated in the GUI.

I use v1.1.8 of Obsidian.

![Screenshot_20221221_065733](https://user-images.githubusercontent.com/30142914/208833235-74a004d3-8f46-4931-a929-8ae917b9ad56.png)

**Comment by ericaxu** [comment]
When was it translated? Probably caused by a delay to port the strings back to the app.

**Comment by henrikfalk** [comment]
Fixed in v.1.1.12
