### ISSUE TITLE
Romanian: the translation shouldn't be considered finished

### ISSUE THREAD

**Issue by kkriszel** [obsidianmd/obsidian-translations#751]
The status for the Romanian language is marked as done in the table in the README, but there are quite a lot of lines that are not translated yet. It should be marked acoordingly, so that translators know that it isn't finished yet.

**Comment by ericaxu** [comment]
I believe the untranslated text are accumulated by new updates of Obsidian. Feel free to open a PR to translate the remaining, or mark it as incomplete if you want to.

**Comment by kkriszel** [comment]
> I believe the untranslated text are accumulated by new updates of Obsidian.

Yes, I thought the same. No worries, I will take my part in translating the rest, as soon as I'm done with Hungarian. :)
