### ISSUE TITLE
How can we remove the word (kismi)?

### ISSUE THREAD

**Issue by ahmetcadirci25** [obsidianmd/obsidian-translations#754]
Turkish language file is complete. Can we remove the word "kismi" from the start screen?

![213931629-62b7cf52-30e8-416d-b270-78ebc39cce5a](https://user-images.githubusercontent.com/9280397/214927466-cf194103-66e6-4415-9949-541853c2ec73.png)

**Comment by ericaxu** [comment]
Starting from next version it will drop the "partial" tag.
