### ISSUE TITLE
"Open linked view" string is not in en.json

### ISSUE THREAD

**Issue by henrikfalk** [obsidianmd/obsidian-translations#755]
I am using v1.1.12

![Screenshot_20230128_085914](https://user-images.githubusercontent.com/30142914/215255683-b4d6586f-20e8-4b54-981f-1d3b69b8f61f.png)

**Comment by liamcain** [comment]
Thanks, will fix!

**Comment by liamcain** [comment]
Added in https://github.com/obsidianmd/obsidian-translations/commit/b1ad1d4f209151110048cd83d68b7f649f5d5f9e
