### ISSUE TITLE
"Create local vault" is not in en.json

### ISSUE THREAD

**Issue by henrikfalk** [obsidianmd/obsidian-translations#756]
Obsidian v1.1.12. Screenshot from "create new vault" modal:

![Screenshot_20230129_104921](https://user-images.githubusercontent.com/30142914/215318590-f4364546-4872-4f7f-b686-8e61ac024e50.png)

**Comment by liamcain** [comment]
Thanks, will fix!

**Comment by ericaxu** [comment]
Will be fixed in the next version!
