### ISSUE TITLE
"Canvas settings" is not in en.json

### ISSUE THREAD

**Issue by henrikfalk** [obsidianmd/obsidian-translations#758]
I cannot find this label in en.json:
![Screenshot_20230211_085711](https://user-images.githubusercontent.com/30142914/218247402-905582b4-e2f2-4c73-a4eb-a0f93a9abecd.png)

**Comment by liamcain** [comment]
Added in https://github.com/obsidianmd/obsidian-translations/commit/b1ad1d4f209151110048cd83d68b7f649f5d5f9e
