### ISSUE TITLE
Add a translation template for the Uzbek language

### ISSUE THREAD

**Issue by azabroflovski** [obsidianmd/obsidian-translations#760]
### Greetings, Obsidian team!

I'm from Uzbekistan 🇺🇿 (Tashkent) it's my native language.
I want to contribute and translate Obsidian into Uzbek. 

Could you add a translation template for Uzbek language?

#### About language
- Language code: `uz`
- Name to display in English: `Uzbek`
- Name in native language: `O'zbek tili`

Thank you!

**Comment by joethei** [comment]
Added the template just now, sorry for the long wait

Thank you for volunteering.

**Comment by azabroflovski** [comment]
> Added the template just now, sorry for the long wait
> 
> Thank you for volunteering.

Thank you
