### ISSUE TITLE
Testing revised German language file

### ISSUE THREAD

**Issue by Jopp-gh** [obsidianmd/obsidian-translations#771]
I changed some inappropriate Denglish (Deutsch - English) words in the German language json file of Obsidian. Like "link" - (Verweis) linking (verweisen, verknüpfen) or "tab" ("Reiter"), etc

First I want to see if my changes are  sufficient, so where do I put this file to  test my changes in Obsidian?

**Comment by joethei** [comment]
This is not possible, the translations are dynamically loaded, so unfortunately there's no good way to test.

There is no location where you could put this file, it's bundled into the application.
