### ISSUE TITLE
Wrong language name

### ISSUE THREAD

**Issue by openforu** [obsidianmd/obsidian-translations#801]
It should be:
**Polski**
not 
**język polski**

![image](https://github.com/obsidianmd/obsidian-translations/assets/27965903/c5d1a2de-8302-49f7-957e-d68cfe78ee70)

**Comment by straurob** [comment]
The above screenshot shows the following menu:  `Settings > About > Language` 

@openforu What does "język polski" mean and in which sense is it incorrect in this context?

**Comment by tomekabc** [comment]
@straurob "język polski" just means "Polish language". He's right, it should be just "Polski". In this menu we have "English" -  not "English language", "Deutsch" - not "Deutsche Sprache" ("German language"), hence we should have just a "Polish" - not a "język polski".

**Comment by ericaxu** [comment]
Fixed in our code and will be available in the next release. Thank you!
