### ISSUE TITLE
[Chinese Simplified]: Update Translation of option-over-size-desc 

### ISSUE THREAD

**Issue by sigrunixia** [obsidianmd/obsidian-translations#851]
Similar to #850, the `option-over-size-desc` of the [zh.json](https://github.com/obsidianmd/obsidian-translations/blob/250a8c7f6554ad0b11d59c523efe3b341c292941/zh.json#L1652) needs updated. This message now displays in Obsidian full time, so needs to be updated to reflect `Your vault is at {{size}} out of {{limit}}.`

**Comment by ericaxu** [comment]
Fixed in https://github.com/obsidianmd/obsidian-translations/commit/e77991ae7bf0e8c680c4e2def8e1ed7ac2834d3b
