### ISSUE TITLE
Core plugins : App, Editor and Files & links description are not translated

### ISSUE THREAD

**Issue by Lisandra-dev** [obsidianmd/obsidian-translations#868]
![image](https://github.com/obsidianmd/obsidian-translations/assets/30244939/75873c3e-3d55-4a80-ad51-28401c2f1f3f)
I can't find them in the translation file (searching with the entire description). 

The other core plugins are translated successfully.

**Comment by Lisandra-dev** [comment]
But these are core plugin and I can't disable them...?

**Comment by lishid** [comment]
There is no core plugin called "App" or "Editor". I think this UI has been tampered by a plugin.

**Comment by joethei** [comment]
Hotkey Helper adds those: <https://github.com/pjeby/hotkey-helper/blob/a360be9d44303233827b121da4f04e7afd84f1f1/src/hotkey-helper.ts#L345-L363>

**Comment by Lisandra-dev** [comment]
Oh, yes. Surprising. Now, I need to found which plugin add this! 

I will close the issue but adding later the plugin culprit for references :)

**Comment by Lisandra-dev** [comment]
Update : the culprit is Hotkey Helper
