### ISSUE TITLE
Missing string in property field context menu

### ISSUE THREAD

**Issue by Acylation** [obsidianmd/obsidian-translations#883]
The option `Remove` seems un-extracted for translation. I'm using v1.4.16.
Checked zh, zh-TW ru and jp.

![image](https://github.com/obsidianmd/obsidian-translations/assets/73122375/6ced66cf-f148-43ea-a54e-3534ededa5b7)

**Comment by liamcain** [comment]
Thanks, will be fixed in the next release!
