### ISSUE TITLE
Missing string "open" in property view

### ISSUE THREAD

**Issue by yo-goto** [obsidianmd/obsidian-translations#898]
Date type property has a button to open an associated daily note. But this "open" string is missing in json files.

![image](https://github.com/obsidianmd/obsidian-translations/assets/50942816/06c2fc4e-ee56-456d-aeaf-ee3d376d4ec6)

File property panel ↓
![image](https://github.com/obsidianmd/obsidian-translations/assets/50942816/bdfb1633-65c1-4b31-af73-a574d8ea20e1)

**Comment by liamcain** [comment]
This should be fixed, thanks!
