### ISSUE TITLE
Missing string "Rename" in All properties panel

### ISSUE THREAD

**Issue by yo-goto** [obsidianmd/obsidian-translations#901]
-> All properties panel -> right click -> "Rename"
This "Rename" string is missing in json files.
![image](https://github.com/obsidianmd/obsidian-translations/assets/50942816/6835bf1d-f0fc-4363-88d6-d889d80a8598)

**Comment by sharkmu** [comment]
What language is this?

**Comment by yo-goto** [comment]
Japanese

**Comment by liamcain** [comment]
This should be fixed now.
