### ISSUE TITLE
Question: Why can't see "ca" language on obsidian

### ISSUE THREAD

**Issue by marczinger** [obsidianmd/obsidian-translations#938]
Hi I don't know if it's only for me, but I can't see the "catalan" "ca" language on the list of languages on the app although it is translated. I tested out the language (via console), but I can't see the release on the "official" build. Is that a matter of time, or it will never be added? 
Thank you!

**Comment by joethei** [comment]
We haven't added it to the app yet, will probably happen soonish.

**Comment by marczinger** [comment]
Ok, thank you again.

**Comment by marczinger** [comment]
Ok, thank you again.

**Comment by suaratrema** [comment]
I am following this issue, with great expectations upon every version update considering it's been completed for a long time. Is that "soonish" to be interpreted in terms of months or years...? :) The Catalan Internet community will receive it very positively!

**Comment by mnguerra** [comment]
Hi,

Does you have any planning for this issue? Could we help in some way? As @suaratrema said, all catalans speakers will receive it positively, we are in fact waiting for it?

Thanks for your job!

**Comment by marczinger** [comment]
Hi, thanks, (gràcies!)  @suaratrema and @mnguerra for the push. For me, is a little disappointing that all the hard work is for nothing. Sure I use the translation with the test trick, but it would be nice that all catalan speakers could have this great piece of software in is native language. @joethei any date for the add? i will update to the last version soon.

**Comment by joethei** [comment]
It's already in the latest version.

**Comment by marczinger** [comment]
Yay! Thank you!

**Comment by mnguerra** [comment]
Wow! @marczinger , thanks for the work! We'll keep an eye to help in future versions!

Also, thanks @joethei for including it!

We'll spread it, not only the catalan translation, but also this good piece of software!
