### ISSUE TITLE
Missing translation "Turn on and reload" in en.json

### ISSUE THREAD

**Issue by henrikfalk** [obsidianmd/obsidian-translations#952]
I just noticed that it is missing in latest en.json and in my language da.json :)

So I cannot translate.

![Screenshot_20240321_073528](https://github.com/obsidianmd/obsidian-translations/assets/30142914/88719b1a-54dd-4c6b-b601-894a1c41ad55)

**Comment by joethei** [comment]
It's `setting.third-party-plugin.button-turn-on`
We changed the english message from "Turn on" to "Turn on and reload", which means that all the translations should also be updated.
We therefore regenerated the strings.
You will be able to translate it again the next time we publish the translation files.
